# Generated by Django 5.0.1 on 2024-01-06 22:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('phone', models.CharField(default='', max_length=50)),
                ('mail', models.CharField(default='', max_length=50, null=True)),
                ('country', models.CharField(default='', max_length=50)),
                ('street', models.CharField(default='', max_length=150)),
                ('city', models.CharField(default='', max_length=50)),
                ('zip_address', models.CharField(default='', max_length=50)),
                ('website', models.CharField(default='', max_length=50)),
                ('ič_dph', models.CharField(max_length=50, null=True)),
                ('dič', models.CharField(blank=True, max_length=50, null=True)),
                ('ičo', models.CharField(blank=True, max_length=50, null=True)),
                ('IBAN', models.CharField(blank=True, default='', max_length=50)),
                ('stamp', models.ImageField(blank=True, null=True, upload_to='')),
                ('DPH', models.BooleanField(default=False)),
                ('dph_size', models.FloatField(default=20.0)),
                ('logo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Admin Information',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.FloatField(default=0.0)),
                ('discount', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, null=True)),
                ('button_url', models.CharField(blank=True, max_length=50, null=True)),
                ('button_text', models.CharField(max_length=50, null=True)),
                ('main_image', models.ImageField(null=True, upload_to='slider/')),
                ('announcement_bar', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='products/')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.products')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('delivery_time', models.CharField(default='', max_length=100, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.shipping')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_ordered', models.BooleanField(default=False)),
                ('status_sent', models.BooleanField(default=False)),
                ('order_price', models.FloatField(default=0.0)),
                ('customer_first_name', models.CharField(default='', max_length=50)),
                ('customer_last_name', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('mail', models.CharField(default='', max_length=50, null=True)),
                ('street', models.CharField(default='', max_length=150)),
                ('city', models.CharField(default='', max_length=50)),
                ('zip_address', models.CharField(default='', max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice', models.FileField(null=True, upload_to='client_invoices/')),
                ('shipping_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.shippingmethod')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.order')),
                ('product_and_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.size')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='slider/')),
                ('slider', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.slider')),
            ],
        ),
    ]
