# Generated by Django 4.0.6 on 2023-10-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_size_name_size_size_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mail',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
