# Generated by Django 4.0.6 on 2023-10-22 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_and_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.size'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.IntegerField(default=0),
        ),
    ]
