# Generated by Django 4.0.6 on 2023-10-22 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_orderitem_product_orderitem_product_and_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='photo',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='static/images/')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.products')),
            ],
        ),
    ]
