# Generated by Django 4.0.6 on 2023-10-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_products_photo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='photo',
            new_name='images',
        ),
    ]
