# Generated by Django 4.0.6 on 2023-10-26 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_shipping_alter_image_images_shippingmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.shippingmethod'),
        ),
    ]
