# Generated by Django 4.0.6 on 2023-10-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_order_invoice_alter_image_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('phone', models.CharField(default='', max_length=50)),
                ('mail', models.CharField(default='', max_length=50, null=True)),
                ('country', models.CharField(default='', max_length=50)),
                ('street', models.CharField(default='', max_length=150)),
                ('city', models.CharField(default='', max_length=50)),
                ('zip_address', models.CharField(default='', max_length=50)),
                ('website', models.CharField(default='', max_length=50)),
                ('account_number', models.CharField(default='', max_length=50)),
                ('IBAN', models.CharField(default='', max_length=50)),
                ('stamp', models.ImageField(upload_to='')),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.CharField(default='', max_length=150),
        ),
    ]
