# Generated by Django 4.0.6 on 2023-10-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_admininformations_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininformations',
            name='dph_size',
            field=models.IntegerField(default=20),
        ),
    ]
