# Generated by Django 4.0.6 on 2023-10-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_admininformations_dph_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininformations',
            name='dph_size',
            field=models.FloatField(default=20.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
