# Generated by Django 4.0.6 on 2023-11-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_admininformations_dph_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admininformations',
            old_name='account_number',
            new_name='dič',
        ),
        migrations.AddField(
            model_name='admininformations',
            name='ič_dph',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admininformations',
            name='ičo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
