# Generated by Django 4.0.6 on 2023-11-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_account_number_admininformations_dič_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoice',
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='delivery_time',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admininformations',
            name='dič',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admininformations',
            name='ič_dph',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admininformations',
            name='ičo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admininformations',
            name='stamp',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
