# Generated by Django 4.0.6 on 2023-12-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_order_status_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.FileField(null=True, upload_to='pdf_invoices/'),
        ),
    ]
