# Generated by Django 4.0.6 on 2023-12-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='images',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='text',
        ),
    ]
