# Generated by Django 4.0.6 on 2023-12-20 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rename_images_slider_image_remove_slider_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='image',
        ),
        migrations.AddField(
            model_name='slider',
            name='Title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='button_text',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='button_url',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='slider/')),
                ('slider', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.slider')),
            ],
        ),
    ]
