# Generated by Django 4.0.6 on 2023-12-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_slider_image_slider_title_slider_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='main_image',
            field=models.ImageField(null=True, upload_to='slider/'),
        ),
    ]
