# Generated by Django 4.0.6 on 2023-12-20 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_image_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
