# Generated by Django 4.0.6 on 2023-12-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_products_options_alter_slide_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininformations',
            name='IBAN',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='admininformations',
            name='dič',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admininformations',
            name='ičo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admininformations',
            name='stamp',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
